# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PriceDrop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PriceDrop
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!
    pod 'Alamofire', '~> 4.4'
end

target 'ProductLink' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProductLink

end

target 'ShareExtension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShareExtension

end
